name: platform_device_id_windows
description: windows implementation of the platform_device_id plugin.
version: 1.0.0
homepage: https://github.com/BestBurning/platform_device_id/tree/master/platform_device_id_windows

environment:
  sdk: ^3.6.0
  flutter: ">=1.22.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      windows:
        pluginClass: PlatformDeviceIdWindowsPlugin
